---
# Variables for default Vagrant VM


# Configure MySQL installation
mysql_db:
  - name: lportal
    replicate: no

mysql_users:
     - name: lportal
       pass: lportal
       priv: "*.*:ALL"


# Configure Java installation - for property documentation see ansible/roles/java/defaults/main.yml
java_oracle_version: 7u51


# Configure Liferay installation
liferay_autodeploy_dir: /vagrant/liferay-deploy

liferay_enable_remote_debug: true
