---

- name: install packages
  tags: mysql
  apt:
    state=latest
    pkg={{item}}
    update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: ensure root access
  tags: mysql
  shell: "echo [client] > ~root/.my.cnf ; cat /etc/mysql/debian.cnf | sed '1,/[client]/d' | sed '/\\[.*/q' | grep -e password -e user >> ~root/.my.cnf ; chmod 600 ~root/.my.cnf"
  # The password should rather be registered here and used in the tasks below. The hack above was invented, because it didn't work out.
  #register: mysql_root_password
  #shell: "cat /etc/mysql/debian.cnf | sed '1,/[client]/d' | sed '/\\[.*/q' | grep password | sed 's/.*=\\s*//'"

- name: create database
  tags: mysql
  mysql_db:
    state=present
    name={{mysql_database_name}}
    collation=utf8_unicode_ci
    encoding=utf8

- name: create user
  tags: mysql
  mysql_user:
    state=present
    name={{mysql_database_user}}
    password={{mysql_database_password}}
    priv={{mysql_database_name}}.*:ALL
